/* BlueMapSignMarkers - scales sign marker icons with the camera distance.
 * Generated by the plugin on every BlueMap (re)load; edit config.yml instead of this file. */
(function () {
    "use strict";

    var CFG = {
        iconSize: %%ICON_SIZE%%,
        enabled: %%SCALING_ENABLED%%,
        refDistance: %%REF_DISTANCE%%,
        exponent: %%EXPONENT%%,
        minScale: %%MIN_SCALE%%,
        maxScale: %%MAX_SCALE%%,
        debug: %%DEBUG%%
    };

    var root = document.documentElement;
    if (CFG.iconSize > 0) root.style.setProperty("--sm-height", CFG.iconSize + "px");
    if (!CFG.enabled) return;

    function getDistance() {
        var app = window.bluemap;
        var viewer = app && app.mapViewer;
        if (!viewer) return null;
        var controls = viewer.controlsManager;
        if (controls && isFinite(controls.distance) && controls.distance > 0) return controls.distance;
        // fallback: distance between the camera and the point it orbits
        if (controls && controls.position && viewer.camera && viewer.camera.position) {
            var a = controls.position, b = viewer.camera.position;
            var d = Math.sqrt(Math.pow(a.x - b.x, 2) + Math.pow(a.y - b.y, 2) + Math.pow(a.z - b.z, 2));
            if (isFinite(d) && d > 0) return d;
        }
        return null;
    }

    var last = -1;
    var warned = false;

    function tick() {
        window.requestAnimationFrame(tick);
        var distance = getDistance();
        if (distance === null) {
            if (CFG.debug && !warned) {
                warned = true;
                console.warn("[SignMarkers] could not read camera distance from window.bluemap");
            }
            return;
        }
        if (last > 0 && Math.abs(distance - last) < last * 0.004) return; // nothing changed
        last = distance;

        var scale = Math.pow(CFG.refDistance / distance, CFG.exponent);
        scale = Math.max(CFG.minScale, Math.min(CFG.maxScale, scale));
        root.style.setProperty("--sm-scale", scale.toFixed(3));
        if (CFG.debug) console.log("[SignMarkers] distance=" + distance.toFixed(1) + " scale=" + scale.toFixed(3));
    }

    window.requestAnimationFrame(tick);
})();
