name: Bluemarks
version: ${version}
main: dev.iaonnis.bluemarks.Bluemarks
api-version: 1.19
folia-supported: true
# Original BlueMapSignMarkers by kugge (https://github.com/KaiijuMC/BlueMapSignMarkers)
authors: [iaonnis, kugge]
depend: [BlueMap]
description: Add markers to BlueMap with signs (fork of BlueMapSignMarkers)
